services:
  - type: web
    name: personal-website
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_EMAILJS_SERVICE_ID
        sync: false
      - key: REACT_APP_EMAILJS_TEMPLATE_ID
        sync: false
      - key: REACT_APP_EMAILJS_PUBLIC_KEY
        sync: false 